site_name: Site Validator Documentation
site_description: Site validator validates HTML and CSS on large sites
repo_url: https://github.com/sitevalidator/docs.sitevalidator.com
extra_css:
  - /css/custom.css
  - /css/highlight/monokai_sublime.css
theme: ""
theme_dir: readthedocs/
pages:
- [index.md, Home]
- [site-wide-validation.md, Site-Wide Validation]
- [validating-your-local-server.md, Validating your Local Server]
- [continuous-validation.md, Continuous Validation]
